language: rust
sudo: false
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache:
  cargo: true
deploy:
  provider: heroku
  app: whispering-shelf-71295
  api_key:
    secure: ChXlmq6d3DtBsmW61fcR1hjfzSmJhmv/HRP0aTaBHENGD54h61W/TVMzrC8qjT8NXPX0jDVR5JK61SEI7lcx8MOrz73tSArX+Fn+cls5lAlOM7Iz/9EHFsfeSjWkCAEBi9Wb1/r8FWuSpCkFyoBxHbtLvJGJ2h5jZVej0h8mV4rQu2zmgpuvYzyWUWeWj1KefIlJ9TFuFmZesXM9cV+I9PeSoGPIf5zJJOgM+A4ruSpsbkzHeFQR925vMqt5e3t3o/sbxEhc5CdBYKafCjFwHxYTvgSmvTowrdLDHOjU0SrvJOPsFMhDeU+slSuDzPlYyAjsZCr5YkfZ3UoK3gO9JHFMNaFP+KiQAFDnO1c3+5QiJUdgo4A/KXFYYF56vAhfSEOgIxTaBmNIAZxYNNPOdly1OBvkqnOcWrgbf6z/MX7dC7SEG11tguczMEmJ1E5GdELF5NjUFBv+kBRY1oHCgP1zzq+HDLEJphaL0cRE3QTxwiNyMMitxKeeREL67H5OC09nnG+cDqHNxYtBm3vppGdskwOKHXCVQUvEri+hqW/vLKBGRmb3Vwit9IDu3ou9AFKoKIUk8KSSsmDZm3D0EdpsUoWleFjqdsUAQFHS6diAYB0ZJ+U3t8mn3Yh+xAbmvsKzopi5cu0CN0mu+SUFr9DcRiA+5Lmok4oFJMb16Ig=
