language: rust
sudo: false
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache:
  cargo: true
deploy:
  provider: heroku
  app: whispering-shelf-71295
  on:
    rust: stable
  api_key:
    secure: FNsDEEpaL0O34g2zJfrCOThHy2kABnBE04B6pYLKDbvHk53mcCDZ/KPYSuhQxU0hlAR8j4U8fz+o8CGoyI0OhipDJ7y9Q8ln39K3N5GdWx0woruRqa6yzfBIPxpppTYxVO13JAqlH67CkGK/HBfZG1AaD+PpHIdCEg2bqLEeBWwPy2YB308xcWSFuqKOtQAJSuatd4fJWrviUGE3k7fUylKqJ6fwn0T83NN1u0bQKjbVJwkHXj3iH0zJzfavVLq4QHZROSS/4JnVE1UIL2GeBzvy7xSAoqPzpEo/LKXFXYq8YEFZ42fBaKTEKQxb0iIlr1HlSZ3bjzAdn9tySwR7/UYZ1Qc35ka9vV1YARKDfRK8fZW40XoelppgwjKfE0jYT//pEkpzjit+Ff5JmE9m/SeMiql1pHy4IMTwsmZRGLLX9URpu9WQhL56CFvhUahPbravW7lIXFJUyb+CbS4GXorzxvlbbm2n8mtyx+ik6YEBnCkpoxaxUtU8gFb2B7RiWTVvCSoQ6pOnI9l2968P/MYATHgPSa1Y1IvdlcxpKyyD9r6hbGZo5UGDlytBCHeyNN+DJtBdlG7jNuKLGpyflpQ+aD9d3UPOgjT9I8D362pJ5LeVuSlYqmLFEcGCizq4Zy7UJ8Ap2B4nQ2s4YgYDijiTaG8refghBOXS2PCL9uE=
