language: rust
sudo: false
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
cache:
  cargo: true
deploy:
  provider: heroku
  app: whispering-shelf-71295
  on:
    rust: stable
  api_key:
    secure: DOhM8WybNOEho7n+U4OKhyFuOvPHcZU7ULbuM08PYC7gVVIgK2Jpua5tR50+LUz43JCR40oqOCuk2hsvD8RfBDUllyxYjqZRUzmK1Vxd0rqXj8ZkD29C/XH96UP28oxyE4BwKIU5Niu3nw2XYWmT5wTjo9JPt7I/CSeFtkLiFm7c4rVcQ7dhoLqsodklUVlHp/lsK2oLnbKgKE8D8kgsqZ2EW39g3eZc6isEbzuHXPg8y/z4nCZZr9JYvnf3WrEDLGftmcVrvxpn22woHN7mdK3q9mmmXmcBB0tCexseX9kA4Vw9vSgN2/DIclOLXibfShtuvXLateL00/GBl2xaj+kT/66O6VAVOZ6yfV5+DNyIk3uYVZNGh8pofM9PLNUICMm+cpzzYsejCooCTEAGjr3MR8sMX1QO3o9Q0tKzv3vnwSP363TX1GILyX4WcbVWkw3tVMBlesOshCR16Q9NUqf40a3Px2JEdCQLSQ0x2t0xufa0BKiepPnYgytjgIjCvuuu5Pfx0PBKA4L+H05WdIz2IGAmZ8pJktK17BCp7snxVDnzuj4HSCwqjYlkwWdEphE1sesBHWrthh3NuJkCiFMz0K1T2i79q44MOIbM+KQzvY2N2iZGi7f5So5hfMr6DxE0/IiZBuilZ3a/l7UdexWHOTa9JUJID8nkEIVvuiQ=
