[package]
name = "httpbox"
version = "0.1.0"
authors = ["Kevin Stone <kevinastone@gmail.com>"]


[dependencies.iron]
version="^0.4.0"
default-features = false

[dependencies.urlencoded]
version="^0.4.0"

[dependencies.logger]
version="*"

[dependencies.router]
version="^0.2.0"

[dependencies.mount]
version="*"

[dependencies.persistent]
version="*"

[dependencies.staticfile]
version="*"

[dependencies.bodyparser]
version="*"

[dependencies.docopt]
version="*"

[dependencies.rustc-serialize]
version="*"

[dependencies.num_cpus]
version="*"

[dependencies.rand]
version="*"

[dependencies.modifier]
version="*"

[dependencies.horrorshow]
version="*"

[dependencies.lazy_static]
version="*"

[dev-dependencies.iron-test]
# version="^0.4.0"
git="https://github.com/reem/iron-test"
rev="86341e56bc4c719e69991c022f4d5b71fbf9c080"

[dev-dependencies.time]
version="*"
