[package]
name = "httpbox"
version = "0.2.0"
authors = ["Kevin Stone <kevinastone@gmail.com>"]

[dependencies]

clap="~2.16.1"
cookie = "0.10"
hyper = "0.11"
futures = "0.1"
futures-timer = "0.1"
horrorshow = "^0.6.2"
lazy_static = "*"
mime = "0.3"
num_cpus = "*"
rand = "*"
serde = "1"
serde_derive = "1"
url = "*"

[dependencies.gotham]
git="https://github.com/gotham-rs/gotham"

[dependencies.gotham_derive]
git="https://github.com/gotham-rs/gotham"
