[package]
name = "httpbox"
version = "0.2.0"
authors = ["Kevin Stone <kevinastone@gmail.com>"]
edition = "2018"

[dependencies]

byteorder="^1.2.4"
clap="~2.16.1"
cookie = "0.10"
either = "1.5"
failure = "0.1.3"
futures = "0.1"
futures-timer = "0.1"
headers = "0.2.0"
http = "0.1"
hyper = "0.12"
horrorshow = "^0.6.2"
lazy_static = "*"
mime = "0.3"
num_cpus = "*"
rand = "^0.5"
serde = "1"
serde_derive = "1"
url = "*"
gotham = "^0.3"
gotham_derive = "^0.3"
tokio = "=0.1.11"
