[package]
name = "httpbox"
version = "0.1.0"
authors = ["Kevin Stone <kevinastone@gmail.com>"]


[dependencies.iron]
version="^0.5.0"
default-features = false

[dependencies.urlencoded]
version="^0.5.0"

[dependencies.logger]
version="*"

[dependencies.router]
version="^0.2.0"

[dependencies.mount]
version="*"

[dependencies.persistent]
version="*"

[dependencies.staticfile]
version="*"

[dependencies.bodyparser]
version="*"

[dependencies.clap]
version="~2.16.1"

[dependencies.rustc-serialize]
version="*"

[dependencies.num_cpus]
version="*"

[dependencies.rand]
version="*"

[dependencies.modifier]
version="*"

[dependencies.horrorshow]
version="^0.6.2"

[dependencies.lazy_static]
version="*"

[dev-dependencies.iron-test]
version="^0.5.0"

[dev-dependencies.time]
version="*"
